name: Deploy
on: [push]
jobs:
  build:
    name: Start Workflow 
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy documentation
          repo: FRIDA-official/Antora-FRIDA-Playbook
          token: ${{ secrets.G_ACCESS_TOKEN }}
         