

    name: Deploy
    # if there is a push on the Antora-UI repository
    on: [push]
    jobs:
      build:
        # Job which uses a docker image with pre installed programms 
        name: Update UI of the Site
        runs-on: ubuntu-latest
        container: 
          image: jonasknebel/resolver_for_yaml_dependencies:latest  
        steps:
          # Checkout the Antora-UI repository on the docker image
          - uses: actions/checkout@master
            with: 
              persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
              fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
              ref: ${{ github.ref }}
          # Install gulp and use it to bundle the files in the repository
          - name: gulp
            run: |
                npm install --global gulp-cli
                npm install --save-dev gulp
                ls
                gulp bundle
          # Add the bundled ZIP to the commit    
          - name: Add files
            run: | 
              git add ./build/*
          # Commit all changed files
          - name: Commit files
            run: |
              git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git config --local user.name "github-actions[bot]"
              git commit -m "Add changes" --allow-empty
          # Push Commits to the branch you are currently on and force the push
          - name: Pushing changes to current branch
            uses: ad-m/github-push-action@master          
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              branch: ${{ github.ref }}  
              force: true
          # Start the workflow of the Antora-FRIDA-Playbook
          - name: Workflow Dispatch
            uses: benc-uk/workflow-dispatch@v1
            with:
              workflow: deploy documentation
              repo: FRIDA-official/Antora-FRIDA-Playbook
              token: ${{ secrets.G_ACCESS_TOKEN }}
         